DROP DATABASE IF EXISTS MediaServer;
CREATE DATABASE IF NOT EXISTS MediaServer;
USE MediaServer;

CREATE TABLE YoutubeMovies (
    id INT NOT NULL AUTO_INCREMENT,
    title VARCHAR(1023),
    url VARCHAR(1023) NOT NULL,
    thumbnail_url VARCHAR(1023) NOT NULL,
    video_id VARCHAR(1023) NOT NULL,
    html_id VARCHAR(1023) NOT NULL,
    video_filename VARCHAR(1023) NOT NULL,
    video_path VARCHAR(1023) NOT NULL,
    download_error BOOLEAN DEFAULT FALSE NOT NULL,
    downloaded BOOLEAN DEFAULT FALSE NOT NULL,
    create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    download_date TIMESTAMP NULL DEFAULT NULL,
    delete_date TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (id),

    UNIQUE KEY video_id (video_id)
);

CREATE TABLE Playlist (
    id INT NOT NULL AUTO_INCREMENT,
    video_fid INT NOT NULL,
    html_id VARCHAR(1023) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT FALSE,
    paused BOOLEAN NOT NULL DEFAULT FALSE,
    create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    delete_date TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (id),

    UNIQUE KEY html_id (html_id)
);

CREATE TABLE PmxPlayers (
    id INT NOT NULL AUTO_INCREMENT,
    ip_address VARCHAR(1023) NOT NULL,
    is_master BOOLEAN NOT NULL,
    PRIMARY KEY (id)
);


GRANT ALL PRIVILEGES ON MediaServer.* TO 'pmxuser'@'%' IDENTIFIED BY 'password' WITH GRANT OPTION;
FLUSH PRIVILEGES;
